FROM node:18-bookworm AS builder
WORKDIR /app
COPY . /app

RUN npm install \
 && cd prerender-server \
 && npm run dist

WORKDIR /app/prerender-server

EXPOSE 5001
ENV API_URL=https://blockstream.info/api/
CMD ["./start.sh"]
